name: Test utils_common
on:
  pull_request:
  push:
    branches:
      - master
      - release-latest
  schedule:
    # Run every hour. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test_ubuntu_melodic_dashing:
    runs-on:  ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        ros_distribution:
          - dashing
          - melodic
    steps:
    - uses: ros-tooling/setup-ros@0.0.25
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}
    - uses: ros-tooling/action-ros-ci@0.0.17
      with:
        package-name: aws_common
    - uses: actions/upload-artifact@v1
      with:
        name: colcon-logs-${{ matrix.os }}
        path: ros_ws/log

  build_and_test_ubuntu_kinetic:
    runs-on:  ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04]
    steps:
    - uses: ros-tooling/setup-ros@0.0.25
      with:
        required-ros-distributions: kinetic
    - run: pip install -U wheel
    - run: python3 -m pip install -U --force-reinstall importlib-resources importlib-metadata
    - uses: ros-tooling/action-ros-ci@0.0.17
      with:
        package-name: aws_common
        source-ros-binary-installation: kinetic
    - uses: actions/upload-artifact@v1
      with:
        name: colcon-logs-${{ matrix.os }}
        path: ros_ws/log

  # build_and_test_asan:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: rostooling/setup-ros-docker:ubuntu-bionic-latest
  #   steps:
  #   # TODO(setup-ros-docker#7): calling chown is necessary for now
  #   - run: sudo chown -R rosbuild:rosbuild "$HOME" .
  #   - uses: ros-tooling/action-ros-ci@0.0.17
  #     with:
  #       colcon-mixin-name: asan
  #       colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
  #       package-name: libstatistics_collector
  #   - uses: actions/upload-artifact@v1
  #     with:
  #       name: colcon-logs-ubuntu-asan
  #       path: ros_ws/log
